### ISSUE TITLE
Doesn't build on Rust 1.14.0

### ISSUE THREAD

**Issue by jeandudey** [alexcrichton/cc-rs#336]
Error:

```rust
error[E0308]: mismatched types
    --> /cc-1.0.19/src/lib.rs:2021:18
     |
2021 |         cmd.args(self.args.iter().filter(|a| !self.removed_args.contains(a)));
     |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected &[_], found struct `std::iter::Filter`
     |
     = note: expected type `&[_]`
     = note:    found type `std::iter::Filter<std::slice::Iter<'_, std::ffi::OsString>, [closure@/cc-1.0.19/src/lib.rs:2021:42: 2021:76 self:_]>`
```

This library is used by the [`rust-bitcoinconsensus`](https://github.com/rust-bitcoin/rust-bitcoinconsensus) which has an strict policy on rustc versions used, this project defaults to use Rust 1.14.0 because it's the only one that is shipped on Debian Stable (`i686`, `arm64`). The main concern for using a fixed rustc version is for deterministic builds and such things.

**Comment by alexcrichton** [comment]
Thanks for the report! Right now this crate doesn't promise anything other than the 2 latest stable releases, but PRs are welcome to add compatibility to older versions where possible!

**Comment by jeandudey** [comment]
The `Command::args` signature has changed since 1.14.0, isn't it a breaking change in the `std` library?
